version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "8080:80"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: seck
      POSTGRES_PASSWORD: 3004
      POSTGRES_DB: campagne
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
